version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8080:80

  python_create_tables:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: python3 db_creation_tables.py
    depends_on:
      - db

  python_insert_tables:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: python3 db_ingestion.py
    depends_on:
      - python_create_tables
  
  python_bookings:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: python3 booking_generator.py
    depends_on:
      - python_insert_tables

  python_rankings:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: python3 ranking_generator.py
    depends_on:

      - python_insert_tables

  # python_adjudication:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   command: python3 validated_bookings.py
  #   depends_on:
  #     - python_rankings
  #     - python_bookings

  #     - python_insert_tables